### ISSUE TITLE
Add way for users to specify color of nodes

### ISSUE THREAD

**Issue by pogi7** [opencaesar/oml-vision#15]
## Checklist before submitting a feature request

- [x] I have reviewed [CONTRIBUTING.md](https://github.com/opencaesar/oml-vision/blob/master/CONTRIBUTING.md) document
- [x] I have done a quick search on the issue tracker to check if the feature request is not redundant

## Is your feature request related to a problem? If yes, describe the problem

It's annoying that the 

```bash
colorKey
```

in the diagramLayouts.json does not allow users to specify the color of nodes.

An example of a node is specified below:
<img width="962" alt="image" src="https://github.com/opencaesar/oml-vision/assets/108915844/b55dfa2a-f5ef-484b-adb8-45a1502845b8">

## Describe the desired feature

Allow users to specify the color of node. Preferably in a GUI
![image](https://github.com/opencaesar/oml-vision/assets/108915844/d222f6c4-d981-487d-a8a9-2f7054f4bc96)

## Additional context

[Any additional context]

**Comment by pogi7** [comment]
Targeted for v0.2.0 release

**Comment by UTNAK** [comment]
In addition to specifying the box color manually, It's nice to have automatic coloring function using colorKey similar to defining color of edges.

<img width="1430" alt="coloring" src="https://github.com/opencaesar/oml-vision/assets/29029659/a41a66d1-cfea-4c3f-8db8-cdbda58bd772">
