### ISSUE TITLE
Add columns to the TreeDiagram

### ISSUE THREAD

**Issue by UTNAK** [opencaesar/oml-vision#35]
## Checklist before submitting a feature request

- [X] I have reviewed [CONTRIBUTING.md](https://github.com/opencaesar/oml-vision/blob/master/CONTRIBUTING.md) document
- [X] I have done a quick search on the issue tracker to check if the feature request is not redundant

## Is your feature request related to a problem? If yes, describe the problem

I would like to add columns to tree diagrams like tables.

## Describe the desired feature

<img width="1427" alt="スクリーンショット 2024-03-12 10 25 51" src="https://github.com/opencaesar/oml-vision/assets/29029659/bf3c3bc1-8ce8-4fd4-bcbf-e96b42b790e3">

**Comment by pogi7** [comment]
@UTNAK This ticket can be closed since a table view meets your use cases.  Please refer to the the [Tables](http://www.opencaesar.io/oml-vision-docs/docs/next/api-documentation/layouts/tables) section in the OML Vision docs for more info.
