### ISSUE TITLE
Specify number as a type in property sheet.

### ISSUE THREAD

**Issue by UTNAK** [opencaesar/oml-vision#43]
## Checklist before submitting a feature request

- [X] I have reviewed [CONTRIBUTING.md](https://github.com/opencaesar/oml-vision/blob/master/CONTRIBUTING.md) document
- [X] I have done a quick search on the issue tracker to check if the feature request is not redundant

## Is your feature request related to a problem? If yes, describe the problem

I would like to specify number as a type in the propertyLayouts.json.

## Describe the desired feature

Please allow users to specify number as a type in the propertyLayouts.json

**Comment by pogi7** [comment]
I want to match the styling to what's recommended here:
https://v2.uiguideline.com/components/number-input

**Comment by pogi7** [comment]
It appears that the maintainers of the VSCode webview UI toolkit won't add in a `number` type to the toolkit.  
https://github.com/microsoft/vscode-webview-ui-toolkit/issues/439
I'll need to extend the definition of their `TextField` to a `NumberField`
https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/text-field/index.ts
